### ISSUE TITLE
闹钟设置界面_AM和PM的样式参考设计稿，且不可以循环滑动。

### ISSUE THREAD

**Issue by youngxkk** [Loop-X/YummyWakeUp-New#13]

**Comment by UFreedom** [comment]
不可以循环滚动的逻辑是什么意思？

@youngxkk

**Comment by youngxkk** [comment]
意思就是AM和PM就像开关一样，只有两种状态，而不是滚轴，可以滚动很多圈

**Comment by UFreedom** [comment]
如果不能滚动的话，该怎么切换呢？

还是说 AM 和 PM的位置固定，用户点击哪个，哪个被选中

**Comment by DONGChuan** [comment]
KK意思是 用户从 AM 滚动到 PM 之后就不能再往前滚了。 只能往回滚动到 AM。
