### ISSUE TITLE
振动的选择应该换为开关样式

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#15]

**Comment by DONGChuan** [comment]
功能上完成。等kk的设计

**Comment by youngxkk** [comment]
https://github.com/glomadrian/material-animated-switch

https://github.com/kyleduo/SwitchButton
这个有那个switch的动画。有material design风格的那个

https://github.com/RomainPiel/Titanic
这个效果更棒

**Comment by DONGChuan** [comment]
使用了推荐的开源控件。 @youngxkk 你测试下。看下怎么样用户看上去舒服。
