### ISSUE TITLE
设置闹钟界面，底部选择按钮应该只有一个为红色

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#17]
1，当前选中的解锁样式为红色
2，其他的为灰色
3.可以考虑加上交互动画，

**Comment by DONGChuan** [comment]
@UFreedom 有bug。 第一次进应用。直接选择默认的正常解锁模式。 进去后底部的按钮为灰色。

**Comment by DONGChuan** [comment]
貌似只有用户第一次进应用的时候会有这个问题

**Comment by UFreedom** [comment]
貌似是ViewPage 的问题
调用 viewPager.setCurrentItem(currentItem, true); 如果 currentItem 等于0，ViewPagerOnTabSelectedListener 的onTabSelected 方法并不会被调用
