### ISSUE TITLE
设置闹钟的时间转盘不流畅，略显卡顿

### ISSUE THREAD

**Issue by youngxkk** [Loop-X/YummyWakeUp-New#2]
中间的时间选择那儿

**Comment by UFreedom** [comment]
这个问题应该是在手指释放时没有处理 释放速度的原因，表明上形成手指一离开，滑动就停止的感觉。
优化方法就是捕获手指释放时的滑动速度，然后让物体做减速运动，这种情况下就会感觉流畅了，

@DONGChuan

**Comment by DONGChuan** [comment]
@UFreedom 我尝试了一晚上 。。

ValueAnimator animation = ValueAnimator.ofInt(1000, 1);
        animation.setInterpolator(new DecelerateInterpolator());
        animation.setDuration(1000);
        animation.start();

```
    animation.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
        public void onAnimationUpdate(ValueAnimator animation) {
            SPEED = (float) animation.getAnimatedValue();
        }
    });
```

想法是这样的。。。我在view里有一个滚动速度 。。我希望这个能减速变化。。。但最后貌似没有效果 。。我尝试了很多组参数 。。

**Comment by UFreedom** [comment]
@DONGChuan  这种方法不可行，

最合适的方法应该是使用 VelocityTracker 跟踪 Touch Up 时的速度，然后使用 Scroller 进行滑动

**Comment by UFreedom** [comment]
@DONGChuan 我用VelocityTracker 和 Scroller 写了一个例子，你看下，代码已经push了，具体的需要优化，我先push上去了，你也研究下，

**Comment by DONGChuan** [comment]
好的!! 有思路就好!!!!

**Comment by DONGChuan** [comment]
我做了细微的调整 尤其是滑动的最大速度限制那。现在用户体验好一点点了。

**Comment by DONGChuan** [comment]
现在滑动速度非常流畅。但有新的issue需要解决
