### ISSUE TITLE
沉浸式顶栏支持

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#23]

**Comment by DONGChuan** [comment]
我尝试了一种沉浸式。而且只有用户向内滑动才会出现状态栏的样式。你看这种怎么养？

**Comment by UFreedom** [comment]
用什么方式
2016年6月30日 上午6:19于 "DONG" notifications@github.com写道：

**Comment by DONGChuan** [comment]
@UFreedom 就是用户直接是看不到顶部的状态栏的。只有用户向内滑动 状态栏才回短暂的弹出来。弹出来的状态栏也是全透明的

如果你觉得不好的话, 我再改成换颜色的那种。
