### ISSUE TITLE
主界面最顶部中间的小图标可以考虑添加打开关闭闹钟的功能

### ISSUE THREAD

**Issue by DONGChuan** [Loop-X/YummyWakeUp-New#25]

**Comment by UFreedom** [comment]
为什么要加这个交互呢

**Comment by DONGChuan** [comment]
因为你想啊, 你左右2个图标都显示状态了。。中间这个一直红色 不就怪怪的么。 而且主界面就可以直接开关闹钟 也很方便啊

**Comment by UFreedom** [comment]
嗯啊。
2016年6月28日 下午9:37于 "DONG" notifications@github.com写道：

**Comment by youngxkk** [comment]
同意这个想法。
也可以当做彩蛋。
