### ISSUE TITLE
设置完闹钟之后改12小时或者24小时制。闹钟显示有问题

### ISSUE THREAD

**Issue by DONGChuan** [Loop-X/YummyWakeUp-New#26]

**Comment by DONGChuan** [comment]
@UFreedom 手机在12小时制和24小时制之前切换时。  sharedpreference 会被清空！！！！你知道为什么吗？

**Comment by UFreedom** [comment]
所有的都会清空？
2016年6月30日 上午3:50，"DONG" notifications@github.com写道：

**Comment by DONGChuan** [comment]
恩 所有的都会清空  我程序里加了LOG仔细看了。 我今晚再查看下具体的SP的文件看看。昨天太晚了。

**Comment by UFreedom** [comment]
嗯嗯…找找广播…是不是广播里面干了啥
2016年6月30日 下午9:52，"DONG" notifications@github.com写道：

**Comment by DONGChuan** [comment]
已确认。SP文件会被覆盖。

**Comment by DONGChuan** [comment]
用土方法fix。

因为数据库不会被覆盖。所以每次都先检测数据库。如果id为1的alarm存在。就直接使用此alarm
