### ISSUE TITLE
部分中文翻译更改

### ISSUE THREAD

**Issue by youngxkk** [Loop-X/YummyWakeUp-New#27]
一：左边栏解锁方式，
1，正常解锁
2，计算解锁
3，拼图解锁
4，摇动解锁

二：主界面：时间下方
起床时间改为：还有xx小时xx分钟  （这个时间是当前距离闹钟所剩下的时间）

**Comment by DONGChuan** [comment]
@youngxkk 已经修改 但还有xx小时xx分钟这个我觉得不好。 现在使用的是和我们手机自带的闹钟相同的说明方式。我觉得还是可以的。
