### ISSUE TITLE
进入闹钟设置界面的逻辑更改

### ISSUE THREAD

**Issue by youngxkk** [Loop-X/YummyWakeUp-New#28]
现在进入闹钟设置是点击时间下方的红色加号
此处要改一下：
加号改为开启和关闭闹钟的功能。  （使用闹钟设置界面的开启和关闭的图标。）

进入闹钟设置界面的入口，从原先的加号改为 起床时间及闹铃时间那两行进入。

**Comment by UFreedom** [comment]
@youngxkk  没懂哎

**Comment by DONGChuan** [comment]
@UFreedom KK的意思是 我们主界面那个加号按钮改成 打开关闭闹钟。

然后用户点击 上面的2个TEXTVIEW 就是显示闹钟时间的那块。 

但我个人觉得这样子用户不友好 至少小学生用这个肯定懵 。。。

**Comment by UFreedom** [comment]
我感觉也是！这个交互有点别扭

.

**Comment by youngxkk** [comment]
那好，这个待定
