### ISSUE TITLE
正常闹钟的解锁方式太过于单调

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#31]
直接点击按钮进行关闭闹钟的交互不太好，我个人感觉还不如去掉这个模式，这个模式太普通了，就像普通闹钟一样，我建议替换成别的模式。

微软的 ：projectoxford 项目 能够进行人脸识别等，我看到 Mimicker Alarm 应用就是用的这个 SDK，闹钟响起时，用户需要拍照，只有是微笑的脸孔才能解锁。

https://www.azure.cn/cognitive-services/zh-cn/pricing

**Comment by UFreedom** [comment]
https://github.com/Microsoft/ProjectOxford-Apps-MimickerAlarm

@DONGChuan  这个是MimickerAlarm  的APP源码

**Comment by DONGChuan** [comment]
好！！我来做

**Comment by DONGChuan** [comment]
Emotion api 要收费。免费的每月有次数限制

**Comment by youngxkk** [comment]
支持使用人脸识别等有意思的方式。

**Comment by youngxkk** [comment]
如果不能用人脸识别，那也同意把正常的解锁方式去掉
