### ISSUE TITLE
在设置闹钟音量时，应该播放当前选择的闹铃

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#33]
现在的情况：
1.选择音量时，没有任何提示音，这样有点不好，用户没法感知到实际的音量是多大，很多应用都是在设置音量的时候就播放音乐，给用户以提示。
2.当试听音乐时，点击音量设置，音乐停止，我感觉不应该立即停止，而是让当前试听铃声的大小跟着音量设置的大小走

**Comment by DONGChuan** [comment]
@UFreedom 选择音量时 我这边更具音量大小有提示音。 你再测试了看看。音量拉到最大的时候很明星的。 这个是闹钟音量,不是媒体音量。

**Comment by DONGChuan** [comment]
我想了下。逻辑上有点怪，
1. 因为滑动seekbar的时候本身就带声音。
2. 在选择铃声的情况下，默认应该声音是最大的，方便用户选择。

@youngxkk 也来考虑下

**Comment by youngxkk** [comment]
支持，
1，所有的软件都是调整的时候，播放当前选中的声音，
2，也支持，应该这样。
