### ISSUE TITLE
任务清单

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#36]
@DONGChuan 
@youngxkk 

目前此应用已经接近尾声，所以我们需要讨论下接下来该做什么事，并提上日程

1.是否迁移项目到私有分支。因为后面我们涉及到渠道发布，所以需要考虑这个问题。
2.LoopX Logo
3.APP  发布渠道
4.埋点，需要了解用户的偏好，以偏于后期功能改善（在私有分支）
5. APP 项目主页

**Comment by DONGChuan** [comment]
我同意转私有分支。但是GITHUB是收费。 可以考虑下 Bitbucket。 5人以下的团队是免费的。但是GITHUB这边的代码如何处理？

**Comment by DONGChuan** [comment]
APP 项目主页这一点我建议就使用 GITHUB 就好。我有制作 jekyll 的基础知识。大家也可以一起加入进来。毕竟后面项目都得有主页。 可以做个模板出来。

我个人支持类似这样的主题。https://github.com/t413/SinglePaged

**Comment by UFreedom** [comment]
这有个文章 https://gist.github.com/jcaraballo/1982605

我感觉在 github 和 Bitbucket 应该可以进行同步，这个需要研究下。能不能在 github 和 Bitbucket 之间进行分支合并，挑选之类的事情

@DONGChuan  你对git的理解比我清楚，你可以试试研究下

**Comment by DONGChuan** [comment]
迁移可以。 同步的话需要用到WEBHOOK。也不难。  但是我想弄明白这个私有分支是用来做以后的开发吗？  GITHUB这边的代码如何处理，只维护初版？

**Comment by youngxkk** [comment]
才看到。
1，我不懂，你们定。
2，loopx的logo周末前搞定。
3，发布渠道及方式最近几天我去和做过渠道的人做个了解。周5下班前确定。
4，埋点你们来定，我不太了解。
5，项目主页是需要一个官方网站吗？

**Comment by UFreedom** [comment]
@youngxkk  项目主页就是一个简单介绍 当前项目的页面，一个页面就够了

**Comment by UFreedom** [comment]
@DONGChuan 
@youngxkk 

我把几个问题单独提出来讨论，都在一起有点乱

**Comment by DONGChuan** [comment]
几个任务都已单独列出
