### ISSUE TITLE
随着秒针一起转的小月亮图标需要固定吗？

### ISSUE THREAD

**Issue by DONGChuan** [Loop-X/YummyWakeUp-New#38]
还有记得白天替换成太阳

**Comment by UFreedom** [comment]
！，这个我忘记写这个逻辑了

**Comment by youngxkk** [comment]
太阳图片上面有

**Comment by UFreedom** [comment]
这个我来弄吧…当时忘记了

**Comment by DONGChuan** [comment]
@UFreedom 我这边测试没看到这个效果啊。 而且我这边晚上显示的图标是太阳

**Comment by UFreedom** [comment]
早 6点 ~ 晚6点 显示太阳图标，
其他显示月亮图标

**Comment by youngxkk** [comment]
小月亮图标需要固定吗？
我建议那个图标固定在闹钟的时间上。白天就显示太阳，晚上显示月亮。
跟着秒针转运，2个一起，感觉有点多余
