### ISSUE TITLE
主界面，右边栏，振动功能的设置，灵敏度需要提高哦，小红点要从这头拉到那头才切换成功

### ISSUE THREAD

**Issue by youngxkk** [Loop-X/YummyWakeUp-New#4]
其实小红点可以拉到一半就自动给拉满，代表功能的开启。

或者最简单的方法：振动设置区域，点击即代表切换振动开关

**Comment by DONGChuan** [comment]
建议改成类似TOGGLE按钮的形式。目前代码里用的是SEEKBAR.

**Comment by UFreedom** [comment]
@youngxkk  @DONGChuan 
振动设置那个使用 SeekBar 不是代表可以自定义振动的强度吗，Android 里面振动的强度可以设置的。

还是说那个只是一个振动的开关，并不能设置强度

**Comment by DONGChuan** [comment]
关键是这里调节震动强度对于用户而言有没有必要？如果可以增强用户体验的话就加上。

**Comment by UFreedom** [comment]
我感觉也是没必要，要是只要一个开关即可
@youngxkk

**Comment by DONGChuan** [comment]
已经改成toggle button
