### ISSUE TITLE
App 的最终名称

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#44]
YummyTimeWakeUP？这个貌似一直没定，现在应该定下来了

**Comment by DONGChuan** [comment]
首先要有中文名和英文名。 尽量简洁 ~ YummyTimeWakeUP 作为应用名过长。

我建议中文3到5个字 - XXX 闹钟
 英文3个单词 X X Alarm

**Comment by UFreedom** [comment]
嗯嗯是的

**Comment by UFreedom** [comment]
YummyAlarm，优美闹钟

**Comment by UFreedom** [comment]
X Alarm,X 闹钟，

这个X取自  LoopX 的X

**Comment by DONGChuan** [comment]
我喜欢 X 这个方案！

**Comment by youngxkk** [comment]
可以，那就X闹钟

**Comment by UFreedom** [comment]
如果大家都赞同 X 方案，那就名字叫 X Alarm，X 闹钟了。 
@youngxkk @DONGChuan

**Comment by DONGChuan** [comment]
恩 同意
