### ISSUE TITLE
闹钟零点过后有bug

### ISSUE THREAD

**Issue by DONGChuan** [Loop-X/YummyWakeUp-New#47]
24小时制时。 比如设置闹钟为00:24 主界面会显示 24:24. 而且有时候闹钟不会响。

**Comment by DONGChuan** [comment]
而且此时再回到闹钟设置界面。反而变成了23:24

**Comment by UFreedom** [comment]
这个闹钟底层模块有点坑，要不我们重构了？

**Comment by UFreedom** [comment]
我想了想，我们还是重构底层Alarm模块吧，本身代码也不是我们自己写的，我们整个APP也只差这快代码就真的是我们一字字码出来的了。

@DONGChuan 你的意见如何，我们重写这个模块吧。

**Comment by DONGChuan** [comment]
我觉得还是重构吧 。。毕竟好多莫名其妙的错误。今天闹钟也没响。但是我点进闹钟，储存在数据库里读出的闹钟是对的。。好莫名其妙

**Comment by UFreedom** [comment]
嗯嗯…那就重构吧…

**Comment by DONGChuan** [comment]
在新闹钟模块中修复
