### ISSUE TITLE
解锁功能主界面的UI调整

### ISSUE THREAD

**Issue by youngxkk** [Loop-X/YummyWakeUp-New#48]
- [x] 打字闹钟改为 ““打字解锁””
- [x] 底下的"OK"按钮的高度调为55dp， 
- [x] 拼个图 改为 “拼图惊喜”
- [x] 摇动手机改为 "摇动解锁"  并且后面的 感叹号要去掉。
- [x] 点击"OK"按钮的时候 红色从中间放大的动效。然后延迟1秒，让用户知道已经选中了。

**Comment by DONGChuan** [comment]
拼个图 改为 每天拼个图

**Comment by DONGChuan** [comment]
点击"OK"按钮的时候 红色从中间放大的动效。然后延迟0.2秒足够
