### ISSUE TITLE
右边栏的UI间距调整，参考设计稿

### ISSUE THREAD

**Issue by youngxkk** [Loop-X/YummyWakeUp-New#49]
右边栏的UI间距调整，参考设计稿
音量，振动的标题，距离左边缩小的屏幕的间距，感觉现在大概有80DP，设计稿大概40dp
所以要缩小

**Comment by youngxkk** [comment]
问题是下方的进度条需要左对齐

**Comment by UFreedom** [comment]
边距的问题，我感觉刚好啊，看着很舒服，然后那个进度条是应该左对齐

**Comment by UFreedom** [comment]
#
