### ISSUE TITLE
闹钟铃声选择的时候，自动播放声音，关闭声音的办法只有恢复主界面

### ISSUE THREAD

**Issue by youngxkk** [Loop-X/YummyWakeUp-New#5]
可以增加几种暂停声音的事件
例如：1，再次点击此铃声的时候，
2，点击铃声设置之外的区域。

**Comment by UFreedom** [comment]
@youngxkk 
@DONGChuan  

这个需要确认下，确定一个最终的方案

**Comment by DONGChuan** [comment]
@youngxkk @UFreedom 
你们可以参考一下自己的手机   它也是必须按一个按钮 确定/取消 返回之前的界面声音才会停止的. 所以我觉得这里的可以参考第二个建议 2，点击铃声设置之外的区域。 但是这个我不确定如何实现，能不能改成, 只要操作另外2个选项 震动和音量的时候 铃声就会停止？

**Comment by UFreedom** [comment]
暂且定为：

1，再次点击此铃声的时候，
2，点击铃声设置之外的区域。

**Comment by DONGChuan** [comment]
再次点击此铃声的时候 － DONE

**Comment by DONGChuan** [comment]
当操作其它2个ui将会停止铃声

**Comment by DONGChuan** [comment]
@UFreedom 给一个layout加监听器去监听其它区域？什么办法最好啊？
