### ISSUE TITLE
Alarm 模块重构任务

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#52]
- [x] Alarm Model
- [x] DataBase
- [x] Receiver
- [x] AlarmWakeReceiver 需要再处理 PowerManager 吗
- [x] bug 00点的时候 主界面显示24
- [x] 闹钟解锁后. notification 应该取消或者更新

**Comment by DONGChuan** [comment]
重构模块暂时放在 module/Alarm 文件夹

**Comment by UFreedom** [comment]
AlarmWakeReceiver 需要再处理 PowerManager 吗，这个问题是啥个意思

**Comment by DONGChuan** [comment]
@UFreedom 因为原先的代码太老了. 7年前的了. 新的程序是把 wakelock独立出来作为工具类. 而且直接使用的是 wakefulboardrecevier. 比较简洁.
