### ISSUE TITLE
右菜单设置界面，播放闹铃音乐时的bug

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#6]
复现步骤：
1.打开右菜单，播放一个音乐
2.滑动主界面，然后快速划过至左菜单，这时音乐并未停止

**Comment by DONGChuan** [comment]
@UFreedom 这个问题我通过保存view tag来解决的。 但是这个思路只是临时的。如果要单独发布这个自定义view。 后面还是得解决这个bug

我这里的方法是。 但用户滑动过快的话。 onMenuClosed  就不会被调用。 所以 openRightDrawerView 的图标就是打开的图标（红色，关闭时灰色）。把这个图标的id保存到tag里。如果打开左侧栏的时候，右侧栏的图标如果还是打开状态的话，就强制 onMenuClosed 右菜单。这样用户之前的操作也能保留。
