### ISSUE TITLE
关于界面

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#63]
1.介绍 Loopx，开发者，与设计者
2.介绍开源项目
3.分享入口，能够分享我们的应用
4.建议与意见（推荐更加新颖的解锁idea）
- [x] 更新团队邮箱
- [ ] 分享功能地址更新

**Comment by youngxkk** [comment]
关于X-ALARM:
X-ALARM是一个有意思的闹钟应用
希望你早上是笑着起床的 ：) 

我们提供的默认闹铃声音是非常舒缓的钢琴曲（也有大自然的声音），希望你可以在自然中清醒，而不是被其它的闹钟惊吓醒。
当你睁开眼睛解锁闹钟时看到的某个图案可以让你瞬间开心起来。

关于你：
如果你脑洞大开，有很多有趣味的想法可以通过下方的邮件地址联系我们。
如果你想把女朋友的照片放到图片解锁里面仅仅是为了女朋友开心也可以联系我们。

关于程序：
X-ALARM也是一个开源项目，任何感兴趣的开发人员都可以参与开发，包括发现bug，请参观github了解具体信息。
感谢Youngxkk, UFreedom, DONGChuan

联系我们：
loopx@gmail.com
