### ISSUE TITLE
X Alarm 1.0.0 版本 渠道包测试验收任务

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#69]
渠道包 验收分配：

Google Play ： UFreedom

锤子市场： @shilipai

腾讯应用宝市场：@SanQingW

360 市场：

魅族市场：@youngxkk 

小米市场：@shilipai

**验收原则：**
- 无爆机崩溃发生
- 闹钟按照正常时间执行
- UI 显示正常（无图片失真，控件显示异常）

**Comment by youngxkk** [comment]
![s60921-205024](https://cloud.githubusercontent.com/assets/5919034/18711627/6784d28c-803d-11e6-8af0-ca68512744e3.jpg)
1:魅族渠道，右边设计菜单，下方图片变形。测试机器魅蓝NOTE2'
2:右边设置菜单-点击某个声音试听后，按home键，在进入APP后无法关掉此声音。任何操作都关不掉。
