### ISSUE TITLE
闹钟在设定完毕后，第二天不会再执行

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#7]
这个问题需要跟踪下 Alarms 闹钟设定模块

**Comment by UFreedom** [comment]
@DONGChuan  , @youngxkk 
你们也跟踪下这个bug，测试下是不是必现，我现在开始定位这个问题。

**Comment by DONGChuan** [comment]
关起。重启ok

**Comment by DONGChuan** [comment]
我这边第二天没有执行  进入应用显示的时间是对的 8：05. 但是进入闹钟设置界面 滚轮确实 8：59.

**Comment by DONGChuan** [comment]
新闹钟模块已修复
