### ISSUE TITLE
闹钟设定的时间转盘，用户在滑动完毕后，应该总有时间是被选中的

### ISSUE THREAD

**Issue by UFreedom** [Loop-X/YummyWakeUp-New#8]
现在的情况是滑动停止后，会出现时间与时间的空隙被选中，应该处理为总有某个时间被选中。

**Comment by DONGChuan** [comment]
@UFreedom 你是指比如用户停在 24 25中间的位置，不会有时间被选中？

**Comment by DONGChuan** [comment]
我记得这种情况下，转盘会自动根据离哪个近移动到24或者25

**Comment by DONGChuan** [comment]
这个问题的关键是在 fling 最后一小段内必须让 mMoveLen 慢慢趋紧于0 。。。。但是我需要有空和你语音下 。。锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕锕  好多细节方面折腾死我了 。。我光看api doc 理解不能。。。。
